#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later

build() {

    add_binary /usr/lib/vsrfdi/vsrfdi

    add_binary /usr/lib/vsrfdi/ask
	
	if [ ! -f "$BUILDROOT/usr/bin/sleep" ]; then
    
		add_binary /usr/bin/sleep
    
    fi
    
    add_file /etc/vsrfdi/pub
    
    add_file /usr/lib/systemd/system/vsrfdi.service
    
    add_symlink /usr/lib/systemd/system/sysinit.target.wants/vsrfdi.service ../vsrfdi.service
	
	add_file /usr/lib/systemd/system/vsrfdi-ask.service

}

help() {
    cat <<HELPEOF
This hook provides the vsrfdi which can help you verify some rootfs files during initramfs.
HELPEOF
}